server:
  port: 5000

spring:
  datasource:
    username: root
    password: JY@class4579
    url: jdbc:mysql://localhost:3306/products
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true